name: Test Bevy Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository code
    - uses: actions/checkout@v4
    
    # Set up Rust toolchain
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    # Cache Rust dependencies
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
    
    # Install Bevy dependencies (for Ubuntu)
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2-dev \
          libudev-dev \
          pkg-config
    
    # Run tests
    - name: Run tests
      run: cargo test --verbose
    
    # Optional: Check formatting
    - name: Check formatting
      run: cargo fmt --all -- --check
    
    # Optional: Run clippy for linting
    - name: Run clippy
      run: cargo clippy -- -D warnings
